### PR TITLE
Set Replicate API token and predictId as environment variables

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
## Proposed changes

- Set Replicate API token and predictId (for testing) as environment variables in ".env" file instead of hard-coding them.
- Add setup instructions (".env" file) and test coverage instructions to README.

### CODE REVIEW

**Comment by sausheong** [comment]
`.env` files are usually not part of a package. You should use them in your application instead.

**Comment by elliotwutingfeng** [comment]
How about loading the API key from the os?

**Comment by sausheong** [comment]
Yes, you should do it in your application. It's not suitable to be in a package.

**Comment by elliotwutingfeng** [comment]
I see, thanks for the advice. Was asking because env variables were used for the API key in [here](https://github.com/sausheong/openai/blob/main/openai_test.go#L18).

**Comment by sausheong** [comment]
Yes that was for testing purposes. I had it on my local machine for testing, you are supposed to load it in your own `.env` file and use your own access key and API. But it's good feedback and documentation could be better :) I whipped this up quickly to solve my own problem.

**Pull request closed without merging**
